# Generated by Django 3.0.3 on 2020-03-01 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('number', models.CharField(max_length=15, unique=True, verbose_name='학번')),
                ('name', models.CharField(max_length=15, null=True, verbose_name='이름')),
                ('gender', models.CharField(max_length=15, null=True, verbose_name='성별')),
                ('email', models.EmailField(max_length=255, null=True, unique=True, verbose_name='이메일')),
                ('phone', models.CharField(max_length=15, null=True, verbose_name='전화번호')),
                ('college', models.CharField(max_length=15, null=True, verbose_name='단과대')),
                ('major', models.CharField(max_length=15, null=True, verbose_name='전공')),
                ('grade', models.IntegerField(null=True, verbose_name='학년')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
