# Generated by Django 3.0.3 on 2020-03-02 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20200302_0210'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='rand',
            field=models.IntegerField(null=True, verbose_name='code'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_is_active',
            field=models.IntegerField(null=True, verbose_name='user_is_active'),
        ),
    ]
