# Generated by Django 3.0.3 on 2020-03-02 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='portfolio',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
